### ISSUE TITLE
Excluded tests in several modules

### ISSUE THREAD

**Issue by GeorgFette** [ethercis/ehrservice#11]
Hello,
In most of the gradle files many tests are explicitely excluded. Why is that so ? I have seen that one reason are file paths that refer to a "/Development/Dropbox/..." path. Can't those files be included in the projects or is this prevented by confidential or intellectual rights issues  ?
Greetings
Georg

**Comment by chevalleyc** [comment]
Hi Georg, sorry for the late reply, I do monitor issues only in ethercis/ethercis (well GitHub...). We are in the process of changing the way EtherCIS is built introducing continuous integration and this will support tests. The issue so far was that tests were dependent on DB state. The missing files will be included in the source repository as well.

**Comment by serefarikan** [comment]
@GeorgFette  please follow https://github.com/ethercis/ethercis/issues/106 The tests in the develop branch attempt to deal with this issue where possible, but there is still some work to do.

**Comment by chevalleyc** [comment]
Closed due to no recent activities. Please feel free to reopen if needed. Thanks
