### ISSUE TITLE
Flyway script  V7_meta_cache.sql uses wrong naming pattern

### ISSUE THREAD

**Issue by serefarikan** [ethercis/ehrservice#15]
Flyway refuses to process the V7_meta_cache.sql file with the following error

`Flyway “Wrong migration name format”...`

This file is introduced with the v1.2 update. I'm guessing renaming it to something like `V7__meta_cache.sql` would solve the problem.

**Comment by chevalleyc** [comment]
Changed the file name with two underscores (for the price of one!)

**Comment by serefarikan** [comment]
Tested it and it works. Thanks @chevalleyc
