### ISSUE TITLE
There is an error in the V9 migration script

### ISSUE THREAD

**Issue by robert-hunter-nes** [ethercis/ehrservice#20]
There appears to be some duplication in the V9__feeder_audit.sql script, and some syntax errors.

**Comment by serefarikan** [comment]
I'm sure the maintainers would appreciate a bit more detail regarding your findings @robert-hunter-nes Care to provide the details re duplication and errors?

**Comment by robert-hunter-nes** [comment]
Sure, each of the 4 tables and the 2 alter statements adding the constraints are being done twice.

Additionally after the first time the ehr.feeder_system_item_ids constraint is added there is a syntax error immediately after it.

**Comment by anon100** [comment]
I've just hit the same issue - trying an install of ethercis (v1.2) today following the installation instructions (https://github.com/ethercis/deploy-n-scripts) and hit this same problem within the install-ethercis-db.sh script. I'm completely new to the project.

Error is: [install-ethercis-error.txt](https://github.com/ethercis/ehrservice/files/3135236/install-ethercis-error.txt) (Looks like the create table statement for ehr.feeder_system_audit is missing a closing bracket).

But I think it's breaking the initial create database stage, as 
"./ecis-server start" then doesn't start, and fails with a sql error (template.crc does not exist)
[ecis-server-error.txt](https://github.com/ethercis/ehrservice/files/3135245/ecis-server-error.txt)

**Comment by robert-hunter-nes** [comment]
@anon100 I think that may be a different issue (EDIT: the template.crc part I mean) you have seen, this one is specific to v1.3.0

**Comment by robert-hunter-nes** [comment]
Closing issue as this has been resolved.
