### ISSUE TITLE
Problem parsing an OPT to JSON

### ISSUE THREAD

**Issue by lreis123** [ethercis/ehrservice#9]
Hello

I am trying to use “ehrservice OPT parser” to perform an OPT parser to JSON format. I'm just using the openEHR.v1.OperationalTemplate-1.0.1.jar, which contains the parser. It turns out that, when I run the parse in Eclipse, I get the following error: 
"com.fasterxml.jackson.databind.JsonMappingException: Could not get a Java numeric type from a Schema complex type (through reference chain: org.openehr.schemas.v1.impl.OPERATIONALTEMPLATEImpl["language"]->org.openehr.schemas.v1.impl.CODEPHRASEImpl["terminologyId"]->org.openehr.schemas.v1.impl.TERMINOLOGYIDImpl["bigIntegerValue"])", generating an incomplete JSON file:
{  
   "language":{  
      "terminologyId":{  
         "value":"ISO_639-1",
         "immutable":false,
         "nil":false,
         "domNode":"<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n<terminology_id xmlns=\"http://schemas.openehr.org/v1\">\n      <value>ISO_639-1</value>\n    </terminology_id>",
         "_child_element_order_sensitive":false,
         "default":false

Any idea to solve this problem?

Note: I using the demo template “prescription”, found in project.

Thank you very much.

Greetings,

Luís Reis

**Comment by chevalleyc** [comment]
Closed due to no recent activities. Please feel free to reopen if needed. Please note that issues should be posted into ethercis/ethercis issues section. Thanks
